server.port: 8888
spring.application.name: configserver

spring.profiles.active: git

spring.cloud.config.server.git.uri: https://github.com/<USERNAME>/<REPOSITORY>
spring.cloud.config.server.git.searchPaths: "{application}"
spring.cloud.config.server.git.username: <EMAIL-GITHUB>
spring.cloud.config.server.git.password: <PERSONAL-TOKEN>
spring.cloud.config.server.git.force-pull: true

spring.security.user.name: <USERNAME-APPLICATION>
spring.security.user.password: <PASSWORD-APPlication>
